apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground1
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: playground
      version: v1
  template:
    metadata:
      labels:
        app: playground
        version: v1
    spec:
      containers:
      - name: playground-c
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground2
  namespace: dev
spec:
  replicas: 0
  selector:
    matchLabels:
      app: playground
      version: v2
  template:
    metadata:
      labels:
        app: playground
        version: v2
    spec:
      containers:
      - name: playground-c
        image: wil42/playground:v2
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: playground
  namespace: dev
spec:
  selector:
    app: playground
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
