apiVersion: v1
kind: Pod
metadata:
  name: playground
  namespace: dev
spec:
  containers:
    - name: playground
      image: wil42/playground:v1
  tolerations:
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
